In [1]:
import numpy as np

# Copy & View

In [9]:
var = np.array([1,2,3,4,5])
copy = var.copy()

var[1] = 20

print('var', var)
print('copy', copy)

var [ 1 20  3  4  5]
copy [1 2 3 4 5]


In [10]:
x = np.array([10,20,30,40,50])
view = x.view()

x[1] = 2

print('x', x)
print('view', view)

x [10  2 30 40 50]
view [10  2 30 40 50]


# Join Array

In [21]:
var1 = np.array([2,4,6,8,10])
var2 = np.array([1,3,5,7,9])

arr1 = np.concatenate((var1, var2))
print(arr1)

[ 2  4  6  8 10  1  3  5  7  9]


In [22]:
var3 = np.array([[2,4],[6,8]])
var4 = np.array([[1,3],[5,7]])

arr2 = np.concatenate((var3, var4), axis=0)
print(arr2, '\n')

arr3 = np.concatenate((var3, var4), axis=1)
print(arr3, '\n')

[[2 4]
 [6 8]
 [1 3]
 [5 7]] 

[[2 4 1 3]
 [6 8 5 7]] 



In [29]:
var5 = np.array([2,4,6,8])
var6 = np.array([1,3,5,7])

arr4 = np.stack((var5, var6), axis=0)
arr5 = np.stack((var5, var6), axis=1)
arr6 = np.hstack((var5, var6))
arr7 = np.vstack((var5, var6))
arr8 = np.dstack((var5, var6))

print('stack, axis=0:', arr4, '\n')
print('stack, axis=1', arr5, '\n')
print('hstack', arr6, '\n')
print('vstack', arr7, '\n')
print('dstack', arr8, '\n')

stack, axis=0: [[2 4 6 8]
 [1 3 5 7]] 

stack, axis=1 [[2 1]
 [4 3]
 [6 5]
 [8 7]] 

hstack [2 4 6 8 1 3 5 7] 

vstack [[2 4 6 8]
 [1 3 5 7]] 

dstack [[[2 1]
  [4 3]
  [6 5]
  [8 7]]] 



# Split Array

In [47]:
var1 = np.array([2,4,6,8,10,12])

split1 = np.array_split(var1, 3)
print(type(split1), split1)
print(split1[1], '\n')

var2 = np.array([[2,4,6],[8,10,12]])

split2 = np.array_split(var2, 2, axis=1)
print(type(split2), split2)
print(split2[1])

<class 'list'> [array([2, 4]), array([6, 8]), array([10, 12])]
[6 8] 

<class 'list'> [array([[ 2,  4],
       [ 8, 10]]), array([[ 6],
       [12]])]
[[ 6]
 [12]]


# Search in NumPy Array

- Search in array for a certain value
    - Returns the index of the elements that are matched

In [56]:
var = np.array([1,5,2,17,9,6,3,15,2,38,53,24,32,2])

x = np.where(var==2)
print(x, '\n')

x = np.where(var/2==0) # returns index of the elements to be searched
print(x, '\n')

x = np.where(var%2==0) # returns index of the elements to be searched
print(x, '\n')

(array([ 2,  8, 13], dtype=int64),) 

(array([], dtype=int64),) 

(array([ 2,  5,  8,  9, 11, 12, 13], dtype=int64),) 



# Sort NumPy Array

In [79]:
var = np.array([1,5,2,17,9,6,3,15,2,38,53,24,32,2])
print(var, '\n')

var = np.sort(var) # Sort the numpy array
print(var, '\n')

[ 1  5  2 17  9  6  3 15  2 38 53 24 32  2] 

[ 1  2  2  2  3  5  6  9 15 17 24 32 38 53] 



In [80]:
var = np.array(['z','d','a','f','y','t'])
print(var, '\n')

var = np.sort(var) # Sort the numpy array
print(var, '\n')

['z' 'd' 'a' 'f' 'y' 't'] 

['a' 'd' 'f' 't' 'y' 'z'] 



In [81]:
var = np.array([[1,5,2,17,9,6],[3,15,2,38,53,24]])
print(var, '\n')

var = np.sort(var) # Sort the numpy array
print(var, '\n')

[[ 1  5  2 17  9  6]
 [ 3 15  2 38 53 24]] 

[[ 1  2  5  6  9 17]
 [ 2  3 15 24 38 53]] 



# Search in a Sorted NumPy Array

- Returns the index where specified value can be inserted to maintain the order

In [73]:
var = np.array([1,5,2,17,9,6,3,15,2,38,53,24,32,2])
var = np.sort(var) # Sort the numpy array
print(var, '\n')

x = np.searchsorted(var, 100) # returns index where the elements can be inserted
print(x, '\n')

x = np.searchsorted(var, 0) # returns index where the elements can be inserted
print(x, '\n')

x = np.searchsorted(var, 24) # returns index where the elements can be inserted
print(x, '\n')

x = np.searchsorted(var, 17) # returns index where the elements can be inserted
print(x, '\n')

x = np.searchsorted(var, 24, side='right') # returns index where the elements can be inserted
print(x, '\n')

x = np.searchsorted(var, 17, side='right') # returns index where the elements can be inserted
print(x, '\n')

x = np.searchsorted(var, [14,16,18]) # returns index where the elements can be inserted
print(x, '\n')

x = np.searchsorted(var, [20,22,24], side='right') # returns index where the elements can be inserted
print(x, '\n')

[ 1  2  2  2  3  5  6  9 15 17 24 32 38 53] 

14 

0 

10 

9 

11 

10 

[ 8  9 10] 

[10 10 11] 



# Filter NumPy Array

In [84]:
var = np.array([1,5,7,12])

my_filter = [True,False,True,False]

filtered_arr = var[my_filter]

print(type(filtered_arr), filtered_arr, '\n')

<class 'numpy.ndarray'> [1 7] 



# Part 2: Functions in NumPy Array

## shuffle()

In [103]:
var = np.array([10,9,8,7,6])
print(var, '\n')

np.random.shuffle(var)
print(var, '\n')

[10  9  8  7  6] 

[ 6 10  8  7  9] 



## unique()

In [110]:
var = np.array([1,5,1,2,17,9,5,21,2,2,15,101,23,2])

x = np.unique(var)
print(x, '\n')

x = np.unique(var, return_index=True)
print(x, '\n')

x = np.unique(var, return_counts=True)
print(x, '\n')

[  1   2   5   9  15  17  21  23 101] 

(array([  1,   2,   5,   9,  15,  17,  21,  23, 101]), array([ 0,  3,  1,  5, 10,  4,  7, 12, 11], dtype=int64)) 

(array([  1,   2,   5,   9,  15,  17,  21,  23, 101]), array([2, 4, 2, 1, 1, 1, 1, 1, 1], dtype=int64)) 



## resize()

resize() can create an array of larger size than the original array
<br>

reshape() is used to create a new array of the same size (as the original array) but of different desired dimensions


In [148]:
var = np.array([1,2,3,4,5,6])
x = np.resize(var, (3,6))
print(x, '\n')

print(var.reshape(3,2))
print(var.reshape(3,6)) # gives an error

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]] 

[[1 2]
 [3 4]
 [5 6]]


ValueError: cannot reshape array of size 6 into shape (3,6)

## flatten() & ravel()


- Both flatten() and ravel() are used to convert multi-dimensional arrays into one-dimensional arrays, but the difference is in how they handle memory

    1. **flatten()** creates a **new copy**, and changes to the copy do not affect the original array
    2. **ravel()** returns a **flattened view**, and changes to the flattened view also affect the original array

In [146]:
var = np.array([1,2,3,4,5,6,7,8,9])
x = np.resize(var, (3,3))
print(x, '\n')
print(x.flatten(), '\n------------------------------------------')

print('Flatten:', x.flatten(), '\n')
print('Flatten, order="C":', x.flatten(order='C'), '\n')
print('Flatten, order="F":', x.flatten(order='F'), '\n------------------------------------------')

print('Ravel:', np.ravel(x), '\n')
print('Ravel, order="F":', np.ravel(x, order="F"), '\n')
print('Ravel, order="C":', np.ravel(x, order="C"), '\n')
print('Ravel, order="K":', np.ravel(x, order="K"), '\n')

# Refer documentation for more orders in flatten() and ravel()

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9] 
------------------------------------------
Flatten: [1 2 3 4 5 6 7 8 9] 

Flatten, order="C": [1 2 3 4 5 6 7 8 9] 

Flatten, order="F": [1 4 7 2 5 8 3 6 9] 
------------------------------------------
Ravel: [1 2 3 4 5 6 7 8 9] 

Ravel, order="F": [1 4 7 2 5 8 3 6 9] 

Ravel, order="C": [1 2 3 4 5 6 7 8 9] 

Ravel, order="K": [1 2 3 4 5 6 7 8 9] 



## insert()

In [158]:
var = np.array([1,2,3,4,5,6])
print(var, '\n')

x = np.insert(var, 2, 21)
print(x, '\n')

x = np.insert(var, 2, [101,201,301])
print(x, '\n')

x = np.insert(var, (2,4), 21)
print(x, '\n')

x = np.insert(var, (2,4), 300.14) # Will not accept float value
print(x, '\n')

[1 2 3 4 5 6] 

[ 1  2 21  3  4  5  6] 

[  1   2 101 201 301   3   4   5   6] 

[ 1  2 21  3  4 21  5  6] 

[  1   2 300   3   4 300   5   6] 



In [175]:
var1 = np.array([[1,2,3],[4,5,6]])
print(var, '\n')

x = np.insert(var1, 1, 21, axis=0)
print(x, '\n')

x = np.insert(var1, 2, 21, axis=0)
print(x, '\n')

x = np.insert(var1, 2, 21, axis=1)
print(x, '\n')

x = np.insert(var1, 2, [21,108], axis=1)
print(x, '\n')

x = np.insert(var1, 0, [21,108,1008], axis=0)
print(x, '\n')

[[1 2 3]
 [4 5 6]] 

[[ 1  2  3]
 [21 21 21]
 [ 4  5  6]] 

[[ 1  2  3]
 [ 4  5  6]
 [21 21 21]] 

[[ 1  2 21  3]
 [ 4  5 21  6]] 

[[  1   2  21   3]
 [  4   5 108   6]] 

[[  21  108 1008]
 [   1    2    3]
 [   4    5    6]] 



## append()

In [176]:
var = np.array([1,2,3,4,5,6])
print(var, '\n')

x = np.append(var, 3.14)
print(x, '\n')

[1 2 3 4 5 6] 

[1.   2.   3.   4.   5.   6.   3.14] 



In [189]:
var1 = np.array([[1,2,3],[4,5,6]])
print(var, '\n')

x = np.append(var1, [[21],[101]], axis = 1)
print(x, '\n')

x = np.append(var1, [[21,101,1001]], axis = 0)
print(x, '\n')

[1 2 3 4 5 6] 

[[  1   2   3  21]
 [  4   5   6 101]] 

[[   1    2    3]
 [   4    5    6]
 [  21  101 1001]] 



## delete()

In [195]:
var = np.array([1,2,3,4,5,6])
print(var, '\n')

x = np.delete(var, 2)
print('Array after deleting data at index 2:\n', x)

[1 2 3 4 5 6] 

Array after deleting data at index 2:
 [1 2 4 5 6]


# Matrix Functions in NumPy Arrays

In [204]:
var1 = np.matrix([[1,2,3],[4,5,6]])

var2 = np.array([[1,2,3],[4,5,6]])

print(type(var1), '\n', var1, '\n')
print(type(var2), '\n', var2, '\n')

<class 'numpy.matrix'> 
 [[1 2 3]
 [4 5 6]] 

<class 'numpy.ndarray'> 
 [[1 2 3]
 [4 5 6]] 



In [209]:
var1 = np.matrix([[1,2,3],[4,5,6]])

var2 = np.matrix([[1,2,3],[4,5,6]])

print(var1*var2) # will give an error

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

## dot()

In [212]:
var3 = np.matrix([[1,2,3],[4,5,6]])
var4 = np.matrix([[1,2,3,30],[4,5,6,60], [7,8,9,90]])

print(var3*var4, '\n')
print(np.dot(var3, var4))

[[ 30  36  42 420]
 [ 66  81  96 960]] 

[[ 30  36  42 420]
 [ 66  81  96 960]]


## transpose()

In [217]:
var1 = np.matrix([[1,2,3],[4,5,6]])
print(var1, '\n')

print(np.transpose(var1), '\n') # Transpose of the matrix

print(var1.T) # Transpose of the matrix

[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]] 

[[1 4]
 [2 5]
 [3 6]]


## swapaxes()

In [226]:
var1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(np.swapaxes(var1, 0,1), '\n')

print(np.swapaxes(var1, 1,0))

[[1 4 7]
 [2 5 8]
 [3 6 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## linalg.inv()

In [233]:
var1 = np.matrix([[1,2],[3,4]])

print(var1, '\n')

print(np.linalg.inv(var1), '\n') # inverse of a matrix

[[1 2]
 [3 4]] 

[[-2.   1. ]
 [ 1.5 -0.5]] 



## linalg.matrix_power()

➜ **np.linalg.matrix_power(matrix, n)**
- **n** can take 3 values:
    1. **n = 0**: Identity Matrix
    2. **n > 0**: Power
    3. **n < 0**: Inverse^Power

In [239]:
var = np.matrix([[1,2],[3,4]])
print(var, '\n')

print(np.linalg.matrix_power(var, 2), '\n')

print(np.linalg.matrix_power(var, 0), '\n')

print(np.linalg.matrix_power(var, -2), '\n')

[[1 2]
 [3 4]] 

[[ 7 10]
 [15 22]] 

[[1 0]
 [0 1]] 

[[ 5.5  -2.5 ]
 [-3.75  1.75]] 



## linalg.det()

In [251]:
var = np.matrix([[1,2],[3,4]])
print(var, '\n')

print('Determinant:', np.linalg.det(var))
print('Determinant:', round(np.linalg.det(var)))

[[1 2]
 [3 4]] 

Determinant: -2.0000000000000004
Determinant: -2


In [249]:
var = np.matrix([[1,2,3],[3,4,5],[1,2,3]])
print(var, '\n')

print('Determinant:', np.linalg.det(var))

[[1 2 3]
 [3 4 5]
 [1 2 3]] 

Determinant: 0.0
